# 日本語（デフォルト言語）
ja:
  languageCode: ja
  contentDir: content/ja
  title: "堀井隆斗 | 大阪大学"
  params:
    description: "堀井隆斗（大阪大学 准教授）の個人サイト"

# 英語
en:
  languageCode: en
  contentDir: content/en
  title: "Takato Horii | Osaka University"
  params:
    description: "Personal website of Takato Horii, Associate Professor at Osaka University"