# デフォルト言語（日本語）
ja:
  locale: ja
  contentDir: content/ja
  title: "堀井隆斗 | 大阪大学"
  params:
    description: "堀井隆斗（大阪大学 准教授）の個人サイト"
    hugoblox:
      identity:
        name: "堀井隆斗"

# 英語
en:
  locale: en-us
  contentDir: content/en
  title: "Takato Horii | Osaka University"
  params:
    description: "Personal website of Takato Horii, Associate Professor at Osaka University"
    hugoblox:
      identity:
        name: "Takato Horii"