# 日本語メニュー
main:
  - name: ホーム
    url: /
    weight: 10
  - name: 研究
    url: /#projects
    weight: 20
  - name: 業績
    url: /#publications
    weight: 30
  - name: お知らせ
    url: /#posts
    weight: 40
  - name: アクセス
    url: /#contact
    weight: 50