main:
  - name: プロフィール
    url: /
    weight: 10
  - name: 業績
    url: /#papers
    weight: 11
  - name: 講演
    url: /#talks
    weight: 12
  - name: お知らせ
    url: /#news
    weight: 13
  - name: 職歴
    url: experience/
    weight: 20
  - name: 研究
    url: projects/
    weight: 30
  - name: 授業
    url: courses/
    weight: 40